import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const fira = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fira.className} bg-[#010C15] px-[30px] py-[40px]`}>
        <div className="bg-[#011627] rounded-[8px] border-[1px] border-[#607B96]">
          <Navbar />
          <div className="h-[81vh]">{children}</div>
          <div className="flex items-end">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
